### ISSUE TITLE
Enhance Day One Index and Link Resolution System

### ISSUE THREAD

**Issue by edoardob90** [edoardob90/jrnl#2]
## Background
The current Day One import system needs enhancements to better support incremental updates and link resolution, particularly for alternate usage between Day One and plain text journals.

### 1. Remove `export_source` from `IndexedEntry`
- Replace with `original_journal_name` to store the Day One journal name
- Handle Unicode journal names (including emoji) without modification
- Add validation for proper UTF-8 encoding

### 2. Add Index Last Modified Timestamp
- Add `last_modified` timestamp to track when the index was last updated
- Update `__getitem__` accessor to look in `entries`
- Update timestamp whenever entries are added
- Use for diagnostics and status reporting

### 3. Update Index Structure
- Add top-level `last_modified` field
- Update serialization/deserialization code

### 4. Add Index Status Check
- Add methods to find latest entry date per journal
- Warn users when importing from newer exports
- Provide clear upgrade path

### File Structure
```json
{
  "last_modified": "2024-11-18T10:00:00",
  "entries": {
    "uuid123": {
      "date": "2024-11-18T10:00:00",
      "journal_name": "personal",
      "original_journal_name": "🧪 Test 2"
    },
    "uuid456": {
      "date": "2024-11-18T11:00:00",
      "journal_name": "personal",
      "original_journal_name": "🧪 Test 2"
    }
  }
}
```

### Required Changes:
1. Update `DayOneIndex` class

  - [ ] Add `last_modified` timestamp
  - [ ] Add methods to find latest entry date by journal
  - [ ] Add index status check methods

2. Update `DayOneJSONImporter`

  - [ ] Add index status check before import
  - [ ] Add warning messages for outdated indices
  - [ ] Consider automatic index updates

3. Add utility functions:
  - [ ] Add `extract_journal_name(export_path: Path) -> str`

4. Add new messages:
   - [ ] Index outdated warning
   - [ ] Update success message
   - [ ] Status information

### Testing Requirements
- Unicode journal name handling
- Index update detection
- Link resolution with mixed journal sources
- Last modified timestamp updates
- Latest entry date detection per journal

## Future Considerations
- Add index status to `--diagnostic` output (including `last_modified`)
- Consider adding index stats command
- Plan for handling deleted Day One entries

## Tasks
- [ ] Add `last_modified` to index
- [ ] Update index structure
- [ ] Add Unicode validation
- [ ] Add warning messages
- [ ] Update tests
- [ ] Add example configs
- [ ] Add index status reporting

This enhancement improves the Day One integration by:
1. Simplifying the index structure
2. Adding basic timestamp tracking
3. Supporting incremental updates
4. Maintaining proper Unicode journal name handling
